### ISSUE TITLE
Create OAC admin S3 bucket

### ISSUE THREAD

**Issue by christinklez** [ucldc/cinco#13]

**Comment by amywieliczka** [comment]
In Rikolti, we don't use CloudFormation for s3 buckets because, while technically infrastructure, there's not a world in which we're tearing down and recreating the s3 buckets that house all of our data. We treat them more like static globals - and indeed, the bucket name is often configured as such within a codebase. My sense is that it is the same for OAC? This s3 bucket is the bucket in which all the finding aids, supplemental pdfs, etc are deposited? 

My hunch is that we just want one `cinco` bucket, and within that bucket we'll want `eads`, `supplemental_pdfs`, workflow process artifacts, and reporting artifacts? possibly disambiguated by institution? @everreau does this sound right to you?

**Comment by everreau** [comment]
yes, that sounds right.

**Comment by amywieliczka** [comment]
I've created the `cinco-data` bucket in the pad-prd account. Can also create a `cinco-data-dev` in the pad-dev account if needed. Bucket names exist in a global namespace.
